name: Snapshot

on:
  push:
    branches: [master]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build artifact
        shell: bash
        run: make compile-linux

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: bin/linux/
          file: ./build/package/Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=newrelic/cli:latest
          cache-to: type=inline
          tags: newrelic/cli:latest
